// Package index generates INDEX.md, the published view of every derived
// relationship. It is generated rather than maintained by hand because a frozen
// document cannot be edited to record what happened to it later.
package index

import (
	"bytes"
	"cmp"
	"fmt"
	"slices"
	"strings"
	"time"

	"github.com/archdochq/archdoc/internal/repo"
)

// Generate renders the index for a repository. The output is deterministic:
// `archdoc index --check` compares it byte for byte against the committed file.
func Generate(r *repo.Repo) []byte {
	var b bytes.Buffer
	// The project name is free text from archdoc.json, so it is escaped like
	// every other piece of free text that reaches this file.
	fmt.Fprintf(&b, "# %s index\n\nGenerated by ArchDoc. Do not edit.\n", escape(r.Config().Name))

	// All four sections are always present, so the file does not change shape
	// as the repository grows.
	numbered := []string{"ID", "Title", "Status", "Decided", "Updates", "Updated by", "Obsoletes", "Obsoleted by", "Implemented in"}
	section(&b, "RFCs", numbered, decisionRows(r, repo.TypeRFC))
	section(&b, "ADRs", numbered, decisionRows(r, repo.TypeADR))
	section(&b, "Spec", []string{"Page", "Title", "Includes", "Stale"}, specRows(r))
	section(&b, "Refs", []string{"ID", "Title", "Verified"}, refRows(r))

	return b.Bytes()
}

func section(b *bytes.Buffer, title string, headers []string, rows [][]string) {
	fmt.Fprintf(b, "\n## %s\n\n", title)
	row(b, headers)
	// The separator carries no padding, matching the format in spec/spec/index.md.
	fmt.Fprintf(b, "|%s\n", strings.Repeat("---|", len(headers)))
	for _, cells := range rows {
		row(b, cells)
	}
}

func row(b *bytes.Buffer, cells []string) {
	fmt.Fprintf(b, "| %s |\n", strings.Join(cells, " | "))
}

func decisionRows(r *repo.Repo, t repo.Type) [][]string {
	var rows [][]string
	for _, d := range documentsOfType(r, t) {
		rows = append(rows, []string{
			link(d.ID, d.Path),
			escape(d.FrontMatter.Title),
			status(d),
			date(d.FrontMatter.Decided),
			links(d.FrontMatter.Updates, r.ByID),
			links(d.UpdatedBy, r.ByID),
			links(d.FrontMatter.Obsoletes, r.ByID),
			links(d.ObsoletedBy, r.ByID),
			// Not IncludedIn: the glossary names terms, it does not
			// implement anything, and this column has to agree with the
			// Implemented fact derived from the same list.
			links(repo.ImplementedIn(d.IncludedIn), r.ByPage),
		})
	}
	return rows
}

func specRows(r *repo.Repo) [][]string {
	var rows [][]string
	for _, d := range documentsOfType(r, repo.TypeSpec) {
		stale := ""
		if d.Stale {
			stale = "yes"
		}
		// The slug is the identity, as an identifier is for the other
		// types, so it stays in the first column and the title joins it.
		rows = append(rows, []string{
			link(d.Page, d.Path),
			escape(d.FrontMatter.Title),
			links(d.FrontMatter.Includes, r.ByID),
			stale,
		})
	}
	return rows
}

func refRows(r *repo.Repo) [][]string {
	var rows [][]string
	for _, d := range documentsOfType(r, repo.TypeRef) {
		rows = append(rows, []string{
			link(d.ID, d.Path),
			escape(d.FrontMatter.Title),
			date(d.FrontMatter.Verified),
		})
	}
	return rows
}

// documentsOfType returns the documents of one type, by identifier for numbered
// types and by path for spec pages. Documents() is already in path order, and
// zero padding makes the two agree for numbered types, but the ordering is
// stated here rather than relied upon.
func documentsOfType(r *repo.Repo, t repo.Type) []*repo.Document {
	var found []*repo.Document
	for _, d := range r.Documents() {
		if d.Type == t {
			found = append(found, d)
		}
	}
	key := func(d *repo.Document) string { return d.Path }
	if t.Numbered() {
		key = func(d *repo.Document) string { return d.ID }
	}
	slices.SortFunc(found, func(a, b *repo.Document) int { return cmp.Compare(key(a), key(b)) })
	return found
}

// status renders a status with its qualifiers, comma-separated in a fixed
// order, so that a document which is both reads as one cell rather than two
// special cases.
func status(d *repo.Document) string {
	// Escaped like every other free-text cell. A status is one of five plain
	// words when the document is valid, but it is whatever the front matter
	// says, and this was the only cell that skipped the escaping.
	return escape(StatusOf(string(d.FrontMatter.Status), !d.FrontMatter.Backfilled.IsZero(), d.EffectivelyObsolete))
}

// StatusOf renders a status with its qualifiers, comma-separated in a fixed
// order, so a document that is both reads as one cell rather than two special
// cases.
func StatusOf(status string, backfilled, obsolete bool) string {
	var qualifiers []string
	if backfilled {
		qualifiers = append(qualifiers, "backfilled")
	}
	if obsolete {
		qualifiers = append(qualifiers, "obsolete")
	}
	if len(qualifiers) == 0 {
		return status
	}
	return fmt.Sprintf("%s (%s)", status, strings.Join(qualifiers, ", "))
}

func link(text, path string) string {
	return fmt.Sprintf("[%s](%s)", escape(text), repo.LinkDestination(path))
}

// links renders names as markdown links to the documents lookup finds for
// them. A name that resolves to nothing is left as text; L04 reports it.
func links(names []string, lookup func(string) *repo.Document) string {
	rendered := make([]string, len(names))
	for i, name := range names {
		if d := lookup(name); d != nil {
			rendered[i] = link(name, d.Path)
			continue
		}
		rendered[i] = escape(name)
	}
	return strings.Join(rendered, ", ")
}

func date(t time.Time) string {
	if t.IsZero() {
		return ""
	}
	return t.Format(repo.DateLayout)
}

// escape protects a cell's contents from the table and link syntax.
func escape(s string) string { return repo.EscapeMarkdown(s) }
